# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LRClassifier": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://yyabansu.github.io/Classification_MultiscaleTech/"

git_url = "https://github.com/yyabansu/Classification_MultiscaleTech/tree/master/"

def custom_doc_links(name): return None
